if(NOT DEFINED GAME OR NOT DEFINED ASSETS OR NOT DEFINED OUTPUT)
 message(FATAL_ERROR "GAME, ASSETS and OUTPUT are required")
endif()
file(MAKE_DIRECTORY "${OUTPUT}")
set(save "${OUTPUT}/untouched-save.json")
file(WRITE "${save}" "review runs must not change this save\n")
file(SHA256 "${save}" save_before)

get_filename_component(binary_dir "${GAME}" DIRECTORY)
# Desktop system fonts can hide a broken mobile bundle.
foreach(assets_dir "${ASSETS}" "${binary_dir}/assets")
 foreach(font LilitaOne-Regular.ttf Nunito-SemiBold.ttf)
  if(NOT EXISTS "${assets_dir}/fonts/${font}")
   message(FATAL_ERROR "Required bundled font is missing: ${assets_dir}/fonts/${font}")
  endif()
 endforeach()
endforeach()

function(check_startup name expected)
 set(report "${OUTPUT}/${name}.json")
 execute_process(COMMAND "${GAME}" --fresh --save "${save}" --software --still --frames 2
  --report "${report}" --capture "${OUTPUT}/${name}.png" ${ARGN}
  RESULT_VARIABLE result OUTPUT_VARIABLE output ERROR_VARIABLE error TIMEOUT 30)
 if(NOT result EQUAL 0)
  message(FATAL_ERROR "${name} failed (${result}): ${output}${error}")
 endif()
 file(READ "${report}" json)
 string(JSON interface GET "${json}" interface)
 if(NOT interface STREQUAL expected)
  message(FATAL_ERROR "${name} opened ${interface}, expected ${expected}")
 endif()
 file(SHA256 "${save}" save_after)
 if(NOT save_after STREQUAL save_before)
  message(FATAL_ERROR "${name} changed the ordinary save")
 endif()
endfunction()

# No interface flag and no asset override must launch the packaged current game.
check_startup(bundled-default clay)
check_startup(source-default clay --assets "${ASSETS}")
check_startup(compatibility-alias clay --assets "${ASSETS}" --hud-layout)
check_startup(scene-only scene --assets "${ASSETS}" --scene-only)
foreach(variant fish plants decorations backgrounds tanks all coins pearls fish-details fish-placement-receipt plant-placement decor-placement plant-placement-receipt decor-placement-receipt layout-editor layout-stash tank-full not-enough-coins not-enough-pearls)
 check_startup("shop-${variant}" clay --assets "${ASSETS}" --fixture shop --ui-variant "${variant}")
endforeach()
foreach(fixture tanks tank-switcher bag settings projects rewards)
 check_startup("${fixture}" clay --assets "${ASSETS}" --fixture "${fixture}")
endforeach()

foreach(assets_dir "${ASSETS}" "${binary_dir}/assets")
 foreach(retired tank-menu fish-popover general-dialog currency-shop level-up shop theme controls details skin aquarium fish tanks)
  if(EXISTS "${assets_dir}/${retired}")
   message(FATAL_ERROR "Retired artwork is still packaged: ${assets_dir}/${retired}")
  endif()
 endforeach()
endforeach()
message(STATUS "Current interface starts from source and bundle; previews preserve saves; retired artwork is absent")
